// Generated by CoffeeScript 1.9.1
(function() {
  var initialize;

  initialize = function() {
    var address, geocoder, i, initLat, initLng, initZoom, len, map, mapOptions, marker, markerOption, post, ref;
    initLat = 0;
    initLng = 0;
    initLat = (typeof kodamaps_posts !== "undefined" && kodamaps_posts !== null) && kodamaps_posts.centerLat !== '' ? parseFloat(kodamaps_posts.centerLat, 10) : initLat;
    initLng = (typeof kodamaps_posts !== "undefined" && kodamaps_posts !== null) && kodamaps_posts.centerLng !== '' ? parseFloat(kodamaps_posts.centerLng, 10) : initLng;
    initZoom = (typeof kodamaps_posts !== "undefined" && kodamaps_posts !== null) && kodamaps_posts.zoom !== '' ? parseInt(kodamaps_posts.zoom, 10) : 10;
    address = (typeof kodamaps_posts !== "undefined" && kodamaps_posts !== null) && kodamaps_posts.centerAddr !== '' ? kodamaps_posts.centerAddr : '';
    if (address !== '') {
      geocoder = new google.maps.Geocoder();
      geocoder.geocode({
        'address': address
      }, function(results, status) {
        var i, len, map, mapOptions, marker, markerOption, post, ref;
        if (status === google.maps.GeocoderStatus.OK) {
          initLat = results[0].geometry.location.k;
          initLng = results[0].geometry.location.D;
          mapOptions = {
            zoom: initZoom,
            center: new google.maps.LatLng(initLat, initLng),
            mapTypeid: google.maps.MapTypeId.ROADMAP
          };
          if (document.getElementById("map_canvas")) {
            map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
          }
          ref = kodamaps_posts.postInfo;
          for (i = 0, len = ref.length; i < len; i++) {
            post = ref[i];
            markerOption = {
              position: new google.maps.LatLng(post.lat, post.lng),
              map: map
            };
            if (post.marker) {
              markerOption.icon = post.marker;
            }
            marker = new google.maps.Marker(markerOption);
          }
        }
      });
    } else {
      mapOptions = {
        zoom: initZoom,
        center: new google.maps.LatLng(initLat, initLng),
        mapTypeid: google.maps.MapTypeId.ROADMAP
      };
      if (document.getElementById("map_canvas")) {
        map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
      }
      ref = kodamaps_posts.postInfo;
      for (i = 0, len = ref.length; i < len; i++) {
        post = ref[i];
        markerOption = {
          position: new google.maps.LatLng(post.lat, post.lng),
          map: map
        };
        if (post.marker) {
          markerOption.icon = post.marker;
        }
        marker = new google.maps.Marker(markerOption);
      }
    }
  };

  window.onload = initialize;

}).call(this);
